import { z } from "zod";

import { SPONSOR_TIERS } from "@/lib/tiers";

/**
 * Schemas for everything under /content.
 *
 * These are the contract between whoever edits the content files (a team
 * member, not necessarily a developer) and the components that render them.
 * They are evaluated at build time and throw on the first invalid record, so
 * a malformed sponsor entry fails `pnpm build` loudly rather than shipping a
 * broken sponsor strip to a paying sponsor.
 */

/* -------------------------------------------------------------------------
   Shared primitives
   ------------------------------------------------------------------------- */

/** A path under /public, e.g. "/sponsors/apex-composites.webp". */
const publicPath = z
  .string()
  .regex(
    /^\/[^\s]*$/,
    "must be a root-relative path under /public, e.g. /sponsors/x.webp",
  );

/**
 * A social profile URL — absolute, and stripped of everything after the path.
 *
 * WHY THE QUERY STRING IS REJECTED RATHER THAN TRIMMED
 *
 * "Copy link" in the Instagram and LinkedIn apps appends a share-tracking
 * identifier to the URL — `?igsi=...` on Instagram, `?trk=`/`?originalSubdomain=`
 * on LinkedIn. That identifier is generated by, and tied to, the phone that
 * copied it. Publishing it puts one team member's tracking token in the footer
 * of every page on the site, forever, for every visitor to send back.
 *
 * The URL without it resolves to exactly the same profile, so the parameter is
 * never load-bearing. It is REJECTED rather than silently stripped because the
 * editor who pasted it should learn that the link they copied carries something
 * personal — a silent fix teaches nobody and hides the next one.
 *
 * A fragment is refused on the same grounds: it addresses a position inside a
 * page, which a profile link has no use for.
 */
const socialUrl = z
  .string()
  .url("must be a full URL including https://")
  .refine((v) => v.startsWith("https://"), "must start with https://")
  .refine(
    (v) => !/[?#]/.test(v),
    "must not carry a query string or fragment — you have most likely pasted a " +
      'share link ("Copy link" in the app). Everything from the "?" or "#" ' +
      "onwards is a tracking identifier for the device that copied it; delete " +
      "it and keep the bare profile URL.",
  );

/** An ISO calendar date, e.g. "2026-03-14". */
const isoDate = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}$/, "must be an ISO date (YYYY-MM-DD)")
  .refine((v) => !Number.isNaN(Date.parse(v)), "must be a real calendar date");

/** Image dimensions are mandatory: every image on this site goes through
 *  next/image with explicit width/height so nothing shifts during load. */
const imageRef = z.object({
  src: publicPath,
  width: z.number().int().positive(),
  height: z.number().int().positive(),
  alt: z
    .string()
    .min(1, "alt text is required — describe the image, do not repeat the name"),
});

export type ImageRef = z.infer<typeof imageRef>;

/* -------------------------------------------------------------------------
   site.ts
   ------------------------------------------------------------------------- */

// Re-exported from a zod-free module so client components can use them
// without pulling this file — and Zod — across the boundary.
export { SPONSOR_TIERS, type SponsorTier } from "@/lib/tiers";

/** Which hero implementation renders. See src/components/hero/ScrollCarHero.tsx.
 *  - "sequence": production. Scroll-driven pre-rendered WebP frames on canvas.
 *  - "model":    dev/preview only. Live three.js GLB, lazy-loaded. */
export const HERO_MODES = ["sequence", "model"] as const;
export type HeroMode = (typeof HERO_MODES)[number];

export const siteSchema = z.object({
  /** Short wordmark used in the header and footer. */
  name: z.string().min(1),
  /** Full legal/registered name, used in metadata and the press kit. */
  longName: z.string().min(1),
  university: z.string().min(1),
  /** One line, under ~90 chars. Appears under the hero headline. */
  tagline: z.string().min(1).max(120),
  /** The positioning statement — what we do and why a sponsor should care. */
  positioning: z.string().min(1),
  description: z.string().min(1).max(200),
  /** Canonical origin, no trailing slash. Drives sitemap, OG and robots. */
  url: z
    .string()
    .url()
    .refine((v) => !v.endsWith("/"), "no trailing slash"),
  contactEmail: z.string().email(),
  sponsorshipEmail: z.string().email(),
  /**
   * Social accounts, in display order. Footer of every page.
   *
   * ONLY CONFIRMED ACCOUNTS BELONG HERE. The list shipped for a while with
   * three entries invented from the expected handle format — an Instagram
   * account that was not ours and a YouTube channel that did not exist — and
   * they were live in the footer of every page. A social link is a claim that
   * an account is the team's; do not add one until it has been opened.
   */
  socials: z
    .array(
      z.object({
        label: z.string().min(1),
        href: socialUrl,
        handle: z.string().min(1),
      }),
    )
    .min(1),
  competition: z.object({
    name: z.string().min(1),
    /** e.g. "FS Class" — the class we enter. */
    class: z.string().min(1),
    organiser: z.string().min(1),
    venue: z.string().min(1),
    year: z.number().int().min(2024).max(2100),
    /** ISO 8601 WITH offset. Parsed once, on the server, into an epoch ms so
     *  the countdown never depends on the visitor's locale or DST rules. */
    startsAt: z.string().datetime({ offset: true }),
  }),
  /**
   * Headline stats for the "What is Formula Student" explainer.
   *
   * `value: null` renders as TBC. There is deliberately no "best finish" stat:
   * KUFS has never competed, and a TBC there would invite the reader to assume
   * a result exists that simply has not been typed in.
   */
  stats: z
    .array(
      z.object({
        value: z.string().min(1).nullable(),
        label: z.string().min(1),
        detail: z.string().min(1),
      }),
    )
    .length(3),

  /** The programme's stage. Drives the first-year framing across the site. */
  programme: z.object({
    /** The season this team was founded. */
    foundedYear: z.number().int().min(2020).max(2100),
    /** First competition entry. Null if not yet entered anything. */
    firstCompetitionYear: z.number().int().min(2024).max(2100),
    /** One line establishing that this is season one, said with confidence. */
    seasonOneLine: z.string().min(1),
  }),

  /**
   * The vehicle programme.
   *
   * IMPORTANT: these are the team's TARGETS and working baseline, taken from
   * the first-year benchmarking report — not decided specifications. The
   * architecture is down-selected on 30 September 2026 and frozen on 30
   * October 2026. The site must say "target" and "baseline", never "is".
   */
  vehicle: z.object({
    /** e.g. "Single-motor rear-wheel-drive electric". */
    architecture: z.string().min(1),
    /** e.g. "230–250 kg". */
    targetMass: z.string().min(1),
    /** ISO date the architecture is selected. */
    architectureDownselect: isoDate,
    /** ISO date the concept is frozen. */
    conceptFreeze: isoDate,
    /** Short note on what is and is not yet decided. */
    note: z.string().min(1),
  }),

  /** Public reference links, from the team's own resource list. */
  links: z.object({
    whatIsFormulaStudentVideo: z.string().url(),
    officialFsuk: z.string().url(),
    fsukKeyDates: z.string().url(),
    fsukRulebook: z.string().url(),
    fsResults: z.string().url(),
    firstYearTeamArticles: z.string().url(),
  }),

  /**
   * Indicative AED to USD rate for the sponsorship page.
   * The dirham is pegged, so this does not move — but it is still displayed as
   * an approximation, and it is not fetched live.
   */
  aedToUsd: z.number().positive(),
  /** The four brand values. Verbatim from the brand sheet — do not reword. */
  values: z
    .array(
      z.object({
        title: z.string().min(1),
        description: z.string().min(1),
      }),
    )
    .length(4),

  /** Supporting straplines from the brand sheet, used across sections. */
  straplines: z.array(z.string().min(1)).min(3),

  sponsorship: z.object({
    /** Path under /public. May not exist yet — the UI handles that. */
    prospectusPath: publicPath,
    /** Set false until the PDF is actually committed; the button then
     *  explains itself instead of serving a 404. */
    prospectusAvailable: z.boolean(),
    /** Where sponsorship enquiries go until a real form endpoint exists. */
    enquiryEmail: z.string().email(),
    /** Reasons to sponsor, each with an optional supporting figure.
     *  `value: null` renders as "TBC" rather than an invented statistic. */
    reasons: z
      .array(
        z.object({
          title: z.string().min(1),
          body: z.string().min(1),
          stat: z.object({
            /** A literal value, or null to render TBC. Ignored if `computed`
             *  is set — those come from the roster so they cannot drift. */
            value: z.string().min(1).nullable(),
            label: z.string().min(1),
            computed: z.enum(["headcount", "disciplines"]).nullable().default(null),
          }),
        }),
      )
      .min(3),
  }),

  facultyAdvisor: z
    .object({
      name: z.string().min(1),
      role: z.string().min(1),
    })
    .nullable(),

  hero: z.object({
    mode: z.enum(HERO_MODES),
    /** Number of frames in /public/hero/frames. Must match what
     *  `pnpm render:frames` produced, or the loader will 404. */
    frameCount: z.number().int().min(2).max(600),
    /** Static image shown on mobile, under reduced-motion, and as the
     *  canvas poster before frame 1 decodes. */
    poster: imageRef,
    /** Path to the GLB used by mode "model" and by the frame renderer.
     *  null => use the procedural placeholder car. */
    modelPath: publicPath.nullable(),
  }),
});

export type SiteConfig = z.infer<typeof siteSchema>;

/* -------------------------------------------------------------------------
   sponsors.json
   ------------------------------------------------------------------------- */

export const sponsorSchema = z.object({
  name: z.string().min(1),
  tier: z.enum(SPONSOR_TIERS),
  logo: imageRef,
  url: z.string().url(),
  /** Optional one-paragraph description shown on /sponsors. */
  blurb: z.string().min(1).optional(),
  /** Optional — what they actually give us. Useful for in-kind partners. */
  contribution: z.string().min(1).optional(),
  since: z.number().int().min(2000).max(2100).optional(),
});

/**
 * May be EMPTY. KUFS has no confirmed partners yet, and an empty sponsor list
 * is the honest state for a first-year team — every surface that renders
 * sponsors handles it with a "be the first" state rather than a blank space.
 * The invented example partners that used to live here were removed: a real
 * prospect must never see a fictional logo next to a real ask.
 */
export const sponsorsSchema = z.array(sponsorSchema);
export type Sponsor = z.infer<typeof sponsorSchema>;

/* -------------------------------------------------------------------------
   affiliations.json — other organisations' marks
   ------------------------------------------------------------------------- */

/**
 * Organisations we are affiliated with: the university, the competition, its
 * organiser.
 *
 * THIS IS NOT THE SPONSOR LIST, AND THE RULES ARE NOT THE SAME. A sponsor
 * gives us their logo and asks us to display it. These are third-party
 * trademarks used without a commercial relationship, and Formula Student and
 * IMechE both publish competitor branding guidance that limits when a team may
 * display the event marks and in what form. Stating that we compete is
 * generally fine; using the logo is more constrained.
 *
 * So every entry carries `permissionConfirmed`, and NOTHING RENDERS WITHOUT
 * IT. The flag is not decorative and it is not a to-do marker: it is the
 * render condition, checked in `getAffiliations()`, and it defaults to nothing
 * — there is no default value that could let an entry through by omission.
 *
 * The second condition is that the logo file actually exists. Permission to
 * use a mark is not the same as having been given the correct artwork, and a
 * logo pulled off a search result is neither the right asset nor licensed.
 * Khalifa University is the live example: permission is confirmed, the file
 * has not been supplied, and the entry therefore does not render.
 */
export const affiliationSchema = z.object({
  name: z.string().min(1),
  /**
   * Whether the organisation has confirmed we may display their mark.
   *
   * Required, with no default. Adding an entry is a deliberate act and so is
   * asserting this, and a boolean that defaults to `false` invites the reading
   * that leaving it out is the same as saying no — it is not, it is saying
   * nothing, and this file should not be able to say nothing about permission.
   */
  permissionConfirmed: z.boolean(),
  /**
   * The supplied artwork. `null` until the organisation sends the file.
   *
   * DO NOT point this at a logo downloaded from a search result or lifted off
   * the organisation's website. Universities in particular usually issue a
   * specific lockup for student organisations, which is not the plain
   * university mark — the version supplied matters.
   */
  logo: imageRef.nullish().default(null),
  /** Their site. Shown as a link on the logo. */
  url: z.string().url(),
  /** One short line on what the relationship actually is. */
  relationship: z.string().min(1),
  /**
   * What is still outstanding before this entry can render, in plain words.
   * Never shown on the site — it is read by whoever picks this up next, and it
   * is surfaced by `pnpm check:brand`.
   */
  pending: z.string().min(1).nullable().default(null),
});

export const affiliationsSchema = z
  .array(affiliationSchema)
  .refine(
    (list) => new Set(list.map((a) => a.name)).size === list.length,
    "each organisation may appear only once",
  );

export type Affiliation = z.infer<typeof affiliationSchema>;

/* -------------------------------------------------------------------------
   team.json
   ------------------------------------------------------------------------- */

/**
 * The two divisions the team is organised into.
 *
 * People can sit in both — the CTO Mechanical also leads Chassis, and two of
 * the marketing group also work on sponsorship — so a member carries a list of
 * roles rather than a single subteam. One person, one card, several roles.
 */
export const DIVISIONS = ["Operations", "Engineering"] as const;
export type Division = (typeof DIVISIONS)[number];

/**
 * Operations roles, in display order.
 *
 * This is the canonical list, which means a role with nobody in it IS a
 * vacancy — /team renders it as one and /join recruits for it, both computed
 * rather than maintained by hand. CTO Electrical is currently empty.
 */
export const OPERATIONS_ROLES = [
  "President",
  "Vice President",
  "Secretary",
  "CTO Mechanical",
  "CTO Electrical",
  "Marketing / Media / Outreach",
  "Sponsorship & Finance",
] as const;
export type OperationsRole = (typeof OPERATIONS_ROLES)[number];

/** The eight engineering subteams, in display order. */
export const ENGINEERING_SUBTEAMS = [
  "Aerodynamics",
  "Chassis & Driver Ergonomics",
  "Steering",
  "Suspension",
  "Throttle & Braking Systems",
  "Powertrain & Drivetrain",
  "High Voltage",
  "Low Voltage & Controls",
] as const;
export type EngineeringSubteam = (typeof ENGINEERING_SUBTEAMS)[number];

/** Year of study, as the university records it. */
export const STUDY_YEARS = [
  "Freshman",
  "Sophomore",
  "Junior",
  "Senior",
  "Graduate",
] as const;

/**
 * PRIVACY: the permitted per-person fields are name, role, subteam, year of
 * study and major — and nothing else. The team's internal roster also holds
 * student ID numbers and personal mobile numbers. Those must never enter this
 * repository, in any file, in any form, including comments. There is
 * deliberately no field here that could hold one.
 */
export const teamMemberSchema = z.object({
  name: z.string().min(1),
  year: z.enum(STUDY_YEARS),
  major: z.string().min(1),
  /** Every role this person holds, across both divisions. */
  roles: z
    .array(
      z.union([
        z.object({
          division: z.literal("Operations"),
          title: z.enum(OPERATIONS_ROLES),
        }),
        z.object({
          division: z.literal("Engineering"),
          title: z.enum(ENGINEERING_SUBTEAMS),
        }),
      ]),
    )
    .min(1),
  /**
   * Absent until a headshot exists. The card falls back to initials on navy.
   *
   * OMITTED rather than written as an explicit `null`, and both are accepted:
   * TinaCMS cannot seed a `null` where it expects an object — it throws
   * "Cannot convert undefined or null to object" and refuses to start — so the
   * files leave the key out. `.default(null)` means everything downstream
   * still receives `null` and nothing had to change to read it.
   */
  photo: imageRef.nullish().default(null),
  linkedin: z.string().url().optional(),
});

export const teamSchema = z
  .array(teamMemberSchema)
  .min(1)
  .refine(
    (list) => new Set(list.map((m) => m.name)).size === list.length,
    "each person appears once; give them multiple roles rather than two entries",
  );

export type TeamMember = z.infer<typeof teamMemberSchema>;

/* -------------------------------------------------------------------------
   milestones.json
   ------------------------------------------------------------------------- */

/** Season phases, in order. Drives the grouping on /progress. */
export const MILESTONE_PHASES = [
  "Design",
  "Manufacture",
  "Assembly",
  "Testing",
  "Competition",
] as const;

export type MilestonePhase = (typeof MILESTONE_PHASES)[number];

export const MILESTONE_STATUSES = ["done", "active", "upcoming"] as const;
export type MilestoneStatus = (typeof MILESTONE_STATUSES)[number];

export const milestoneSchema = z.object({
  title: z.string().min(1),
  date: isoDate,
  status: z.enum(MILESTONE_STATUSES),
  description: z.string().min(1),
  /** Which phase of the season this belongs to. Groups /progress. */
  phase: z.enum(MILESTONE_PHASES),
  /** What actually happened, written after the fact. null = not started, and
   *  the page says so rather than inventing an entry. */
  update: z.string().min(1).nullable().optional().default(null),
  /** Photo from the workshop or the track. null until one exists. */
  photo: imageRef.nullish().default(null),
});

export const milestonesSchema = z
  .array(milestoneSchema)
  .min(1)
  .refine(
    (list) => list.filter((m) => m.status === "active").length <= 1,
    "at most one milestone may be 'active' — it is the single 'you are here' marker",
  );

export type Milestone = z.infer<typeof milestoneSchema>;

/* -------------------------------------------------------------------------
   tiers.json — the sponsorship package
   ------------------------------------------------------------------------- */

/**
 * The benefit rows in the tier comparison table, in display order.
 *
 * Fixed keys rather than free-form rows so every tier is compared on exactly
 * the same seven things. A sponsor deciding between Gold and Silver should be
 * able to read across a row, not hunt for whether a benefit was simply omitted.
 */
export const BENEFIT_ROWS = [
  { key: "livery", label: "Logo on the car" },
  { key: "kit", label: "Logo on teamwear" },
  { key: "website", label: "Logo on this site and materials" },
  { key: "social", label: "Social media" },
  { key: "designReport", label: "Competition Design Report" },
  { key: "recruitment", label: "Recruitment access" },
  { key: "recognition", label: "Recognition at events" },
  { key: "labVisit", label: "KUFS lab visit" },
] as const;

export type BenefitKey = (typeof BENEFIT_ROWS)[number]["key"];

const benefitValue = z.union([
  z.string().min(1),
  /** false = not included in this tier. Renders as an em dash, not a blank. */
  z.literal(false),
]);

export const tierSchema = z.object({
  tier: z.enum(SPONSOR_TIERS),
  name: z.string().min(1),
  /** Headline price. null until the team sets it — renders as "TBC". */
  amount: z.string().min(1).nullable(),
  /** One line on what this tier is for. */
  summary: z.string().min(1),
  /** How many partners we will take at this level. null = unlimited. */
  slots: z.number().int().positive().nullable(),
  benefits: z.object({
    livery: benefitValue,
    kit: benefitValue,
    website: benefitValue,
    social: benefitValue,
    designReport: benefitValue,
    recruitment: benefitValue,
    recognition: benefitValue,
    labVisit: benefitValue,
  }),
});

export const tiersSchema = z
  .array(tierSchema)
  .min(1)
  .refine(
    (list) => new Set(list.map((t) => t.tier)).size === list.length,
    "each tier may appear only once",
  );

export type SponsorshipTier = z.infer<typeof tierSchema>;

/* -------------------------------------------------------------------------
   roles.json — open recruitment positions
   ------------------------------------------------------------------------- */

export const roleSchema = z.object({
  title: z.string().min(1),
  subteam: z.enum(ENGINEERING_SUBTEAMS),
  description: z.string().min(1),
  /** What we actually want to see. Kept honest — no "rockstar" language. */
  lookingFor: z.array(z.string().min(1)).min(1),
  /** null = we will take as many good applicants as apply. */
  openings: z.number().int().positive().nullable(),
});

export const rolesSchema = z.array(roleSchema).min(1);
export type Role = z.infer<typeof roleSchema>;

/* -------------------------------------------------------------------------
   cars/<year>.json — the season's car
   ------------------------------------------------------------------------- */

/**
 * Spec rows, in display order.
 *
 * A fixed list rather than free-form keys so the table is comparable between
 * seasons: 2028's car sits beside 2027's and every row lines up. Anything the
 * team has not measured yet is `null` and renders as TBC — an invented figure
 * on a page engineers will read is worse than an admitted gap.
 */
export const SPEC_ROWS = [
  { key: "mass", label: "Mass", unit: "kg" },
  { key: "wheelbase", label: "Wheelbase", unit: "mm" },
  { key: "trackFront", label: "Front track", unit: "mm" },
  { key: "trackRear", label: "Rear track", unit: "mm" },
  { key: "power", label: "Power", unit: "" },
  { key: "drivetrain", label: "Drivetrain", unit: "" },
  { key: "chassis", label: "Chassis construction", unit: "" },
  { key: "laminate", label: "Laminate schedule", unit: "" },
  { key: "suspension", label: "Suspension", unit: "" },
  { key: "tyres", label: "Tyres", unit: "" },
  { key: "downforce", label: "Downforce", unit: "" },
  { key: "brakes", label: "Brakes", unit: "" },
  { key: "electronics", label: "Electronics", unit: "" },
] as const;

export type SpecKey = (typeof SPEC_ROWS)[number]["key"];

/** null renders as TBC. Never fill one of these in with an estimate. */
const specValue = z.string().min(1).nullable();

export const CAR_SUBSYSTEMS = [
  "Aerodynamics",
  "Chassis",
  "Powertrain",
  "Electronics",
  "Suspension",
] as const;

export const carSchema = z.object({
  /** The competition year this car was built for. */
  year: z.number().int().min(2024).max(2100),
  /** The car's name or designation, e.g. "KU-01". */
  name: z.string().min(1),
  /** One line: what this car is and what changed from last season. */
  positioning: z.string().min(1),
  status: z.enum(["concept", "in-build", "testing", "competing", "retired"]),
  spec: z.object({
    mass: specValue,
    wheelbase: specValue,
    trackFront: specValue,
    trackRear: specValue,
    power: specValue,
    drivetrain: specValue,
    chassis: specValue,
    laminate: specValue,
    suspension: specValue,
    tyres: specValue,
    downforce: specValue,
    brakes: specValue,
    electronics: specValue,
  }),
  subsystems: z
    .array(
      z.object({
        name: z.enum(CAR_SUBSYSTEMS),
        headline: z.string().min(1),
        body: z.string().min(1),
        /**
         * Photo or CAD render. Omitted until one exists; see the note on
         * `photo` in teamMemberSchema for why it is absent rather than null.
         */
        image: imageRef.nullish().default(null),
      }),
    )
    .min(1),
  /** May be empty — the page renders an honest empty state. */
  gallery: z.array(imageRef),
});

export type Car = z.infer<typeof carSchema>;

/* -------------------------------------------------------------------------
   news/*.mdx frontmatter
   ------------------------------------------------------------------------- */

export const newsFrontmatterSchema = z.object({
  title: z.string().min(1),
  /** gray-matter turns an unquoted YAML date into a Date; accept both. */
  date: z.union([isoDate, z.date().transform((d) => d.toISOString().slice(0, 10))]),
  author: z.string().min(1),
  excerpt: z.string().min(1).max(280),
  cover: imageRef,
  draft: z.boolean().optional().default(false),
});

export type NewsFrontmatter = z.infer<typeof newsFrontmatterSchema>;

export type NewsPost = NewsFrontmatter & {
  slug: string;
  /** Raw MDX body. Compiled when /news/[slug] is built (a later milestone). */
  body: string;
};

/* -------------------------------------------------------------------------
   newsletter/*.mdx frontmatter
   ------------------------------------------------------------------------- */

/**
 * The monthly newsletter — one file per issue, at
 * content/newsletter/<year>-<month>.mdx.
 *
 * SEPARATE FROM /news, DELIBERATELY. /news is for one-off announcements: a
 * result, a launch, a partnership. The newsletter is a periodical in which
 * each subteam reports its own findings and progress. Merging them would mean
 * a reader subscribing to "what happened" also gets eight engineering reports
 * a month, and a reader who wants the engineering has to sift announcements
 * out of it. They also syndicate separately — /news/rss.xml and
 * /newsletter/rss.xml — which is the clearest evidence they are two things.
 *
 * There is no `title`: an issue is identified by its number and its month, and
 * a hand-typed title is one more thing to contradict them. The heading is
 * composed from `issue`, `month` and `year`.
 *
 * There is no `cover` either. News posts have one because a story needs a
 * picture; an issue is a document, and requiring an image per month is how a
 * newsletter stops being published.
 *
 * THE SUBTEAM SECTIONS ARE NOT IN THE FRONTMATTER. They are the `##` headings
 * of the body, parsed and validated by `getNewsletterIssues()` in
 * src/lib/content.ts against the roster's own subteam list. A subteam that did
 * not contribute is simply absent — see the note there on why nothing renders
 * in its place.
 */
export const newsletterFrontmatterSchema = z.object({
  /** Sequential, from 1. Shown as "Issue 4". */
  issue: z.number().int().positive(),
  /** 1–12. Formatted for display, so an editor cannot type "Oct" one month
   *  and "October" the next, and sorting is arithmetic rather than lexical. */
  month: z.number().int().min(1).max(12),
  year: z.number().int().min(2026).max(2100),
  /**
   * The editor's short introduction to the issue. Plain text, not MDX: it is
   * shown on the issue page and used as the meta description and the RSS
   * summary, and markup in any of those three places is wrong.
   */
  intro: z.string().min(1).max(500),
  /** Same flag, same meaning and same machinery as a news post. */
  draft: z.boolean().optional().default(false),
});

export type NewsletterFrontmatter = z.infer<typeof newsletterFrontmatterSchema>;

/** One subteam's contribution to an issue. */
export type NewsletterSection = {
  subteam: EngineeringSubteam;
  /** Anchor id, for the jump list at the top of the issue. */
  id: string;
  /** Raw MDX, everything under that subteam's heading. */
  body: string;
};

export type NewsletterIssue = NewsletterFrontmatter & {
  /** "<year>-<month>", from the filename. Drives the URL. */
  slug: string;
  sections: NewsletterSection[];
};

/* =========================================================================
   content/copy/*.json — every user-visible word on the site
   =========================================================================

   These schemas exist so a committee lead can reword any page from /admin
   without opening a code editor. They are the same pipeline as everything
   else: Zod here, Tina fields compiled from it by tina/zod-to-tina.ts, plain
   English labels in tina/overlays.ts.

   WHY EVERY FIELD HAS A LENGTH LIMIT

   A CMS that can put a paragraph in a button ships a broken layout. The
   limits below are sized to what the design actually holds at 390px, which is
   the width most of this site's traffic arrives at — not to a round number.
   They are shown as help text in the panel, and they are the reason an editor
   cannot break the layout by typing.

   Measure before changing one. `heading` at 70 is two lines of `text-h1` at
   390px; 90 is three and starts pushing the hero CTA below the fold.

   WHAT IS DELIBERATELY NOT HERE

   - Colours, fonts and spacing. The palette is contrast-verified by
     check:contrast; a CMS that can set a heading to Racing Red on navy ships
     2.12:1. A palette change is a developer request.
   - Routes and URLs. Nav LABELS are editable below; `href` is an enum of the
     routes that exist, so the panel cannot invent, rename or delete a page.
   - Heading levels. An editor changes the words in an h2, never whether it is
     an h2. That is what holds accessibility at 100.
   ========================================================================= */

/** Small all-caps label above a heading. One short phrase. */
const eyebrow = z.string().min(1).max(40);

/** h1/h2 text. 70 characters is two lines of text-h1 at 390px. */
const heading = z.string().min(1).max(70);

/** h3/h4 text, and card titles. Sits in narrower columns, but wraps more. */
const subheading = z.string().min(1).max(90);

/** The standfirst under a section heading. Two to three lines. */
const lead = z.string().min(1).max(280);

/** Body copy. Long enough for a real paragraph, short enough to stay scannable. */
const paragraph = z.string().min(1).max(700);

/**
 * Button text.
 *
 * 32 is measured, not guessed: at 390px a `size="md"` button is 350px wide
 * inside the gutter, less 40px of horizontal padding, and Barlow 600 at 16px
 * averages ~9.7px per character — so 32 characters is the last count that
 * stays on one line. "Download the prospectus (PDF)" is 29 and is the longest
 * button on the site today. Anything past this wraps, and a two-line button
 * next to a one-line button is the first thing that looks broken.
 */
const buttonLabel = z.string().min(1).max(32);

/** Inline link text and small labels. */
const linkLabel = z.string().min(1).max(48);

/** Stat and table labels — these sit in fixed-width columns. */
const microLabel = z.string().min(1).max(36);

/**
 * One short line: a nav description, a glossary term, a response time.
 *
 * Its own primitive rather than `microLabel.max(64)`, because Zod's `.max()`
 * ADDS a rule instead of replacing one — chaining a longer max onto a shorter
 * one leaves the shorter still enforced, and the field silently keeps the
 * limit you thought you had widened.
 */
const shortLine = z.string().min(1).max(64);

/** A caption under an image or a card. Wraps to two or three short lines. */
const captionLine = z.string().min(1).max(140);

/** <title>. Google truncates around 60. */
const metaTitle = z.string().min(1).max(60);

/** <meta description>. Google truncates around 160. */
const metaDescription = z.string().min(1).max(160);

/** Every page carries these two. */
const metaSchema = z.object({
  title: metaTitle,
  description: metaDescription,
});

/** The standard section header: eyebrow, heading, optional standfirst. */
const sectionHeadingSchema = z.object({
  eyebrow: eyebrow,
  title: heading,
  lead: lead.nullish().default(null),
});

/** A titled block of body copy — feature cards, in-kind categories, benefits. */
const titledBodySchema = z.object({
  title: subheading,
  body: paragraph,
});

/** A question and its answer. */
const faqSchema = z.object({
  question: subheading,
  answer: paragraph,
});

/* -------------------------------------------------------------------------
   common.json — header, footer, nav labels, forms, shared calls to action
   ------------------------------------------------------------------------- */

/**
 * Nav LABELS are editable; the route is not.
 *
 * `href` is an enum of the routes that exist, so the panel cannot invent a
 * page, rename a URL or delete `/become-a-sponsor`. src/lib/nav.ts still owns
 * the route list and fails the build if a route loses its label, so the two
 * cannot drift.
 */
export const PRIMARY_ROUTES = [
  "/the-car",
  "/team",
  "/progress",
  "/sponsors",
  "/become-a-sponsor",
  "/news",
  "/newsletter",
  "/join",
] as const;

export const SECONDARY_ROUTES = ["/press-kit", "/contact"] as const;

const navItemSchema = z.object({
  href: z.enum(PRIMARY_ROUTES),
  label: linkLabel,
  description: shortLine,
});

const secondaryNavItemSchema = z.object({
  href: z.enum(SECONDARY_ROUTES),
  label: linkLabel,
});

export const commonCopySchema = z.object({
  nav: z.object({
    primary: z.array(navItemSchema).length(PRIMARY_ROUTES.length),
    secondary: z.array(secondaryNavItemSchema).length(SECONDARY_ROUTES.length),
  }),
  cta: z.object({
    sponsor: buttonLabel,
    join: buttonLabel,
  }),
  header: z.object({
    skipToContent: linkLabel,
    openMenu: linkLabel,
    closeMenu: linkLabel,
  }),
  /**
   * Sitewide SEO keywords. Editable words, but the derived ones — competition
   * name, class, university — are injected by the layout from site.json so
   * they cannot contradict the rest of the site.
   */
  seoKeywords: z.array(shortLine).min(1).max(12),
  footer: z.object({
    exploreHeading: microLabel,
    getInvolvedHeading: microLabel,
    /** "{name}. A student team at {university}." */
    legalLine: lead,
  }),
  comingSoon: z.object({
    badge: microLabel,
    body: paragraph,
    backLink: linkLabel,
  }),
  /**
   * The affiliation strip in the footer. See
   * src/components/layout/AffiliationStrip.tsx.
   *
   * `competingLine` is the claim the site makes WITHOUT using anyone's
   * trademark, and it renders whether or not any logo is cleared. Its
   * {competition}, {year} and {organiser} are filled from site.json so it
   * cannot drift from the countdown or the footer — an editor rewords the
   * sentence around them, and cannot change which competition we say we are
   * entering.
   */
  affiliations: z.object({
    heading: microLabel,
    /** "Competing in {competition} {year}, organised by the {organiser}" */
    competingLine: lead,
  }),
  hero: z.object({
    scrollHint: microLabel,
  }),
  countdown: z.object({
    days: microLabel,
    hours: microLabel,
    minutes: microLabel,
    seconds: microLabel,
    happeningNow: subheading,
    /** "{event} is under way at ..." */
    happeningNowDetail: paragraph,
    finished: subheading,
    finishedDetail: paragraph,
    /** Screen-reader summary. The digits themselves are aria-hidden. */
    remainingSummary: lead,
    loadingSummary: lead,
  }),
  /** Shared UI chrome used on more than one page. */
  ui: z.object({
    logoAlt: shortLine,
    sponsorBarHeading: microLabel,
    linkedinLabel: microLabel,
    /** Milestone status chips. Keys are fixed; the words are not. */
    statusDone: microLabel,
    statusActive: microLabel,
    statusUpcoming: microLabel,
    /** Screen-reader text for the hero's loading progress. "{percent}" */
    heroLoading: lead,
  }),
  /** The sponsorship tier comparison table. */
  tierTable: z.object({
    notIncluded: microLabel,
    tbcLabel: microLabel,
    tbcTooltip: lead,
    /** "≈ USD {amount}" */
    usdApprox: microLabel,
    tableCaption: lead,
    benefitColumnLabel: microLabel,
    purposeRowLabel: microLabel,
    placeSingular: microLabel,
    placePlural: microLabel,
  }),
  /** Sponsorship and contact forms. Both use the same component. */
  form: z.object({
    nameLabel: microLabel,
    organisationLabel: microLabel,
    emailLabel: microLabel,
    messageLabel: microLabel,
    /** Honeypot field. Hidden from sighted users, read by screen readers. */
    honeypotLabel: microLabel,
    submitLabel: buttonLabel,
    submittingLabel: buttonLabel,
    /** Announced to screen readers while the request is in flight. */
    submittingAnnouncement: lead,
    sendAnotherLabel: buttonLabel,
    successTitle: subheading,
    /** "{window}" is replaced with the reply-time phrase below. */
    successBody: paragraph,
    errorTitle: subheading,
    errorBody: paragraph,
    replyPromise: lead,
    mailtoNote: paragraph,
    requiredNote: lead,
    /**
     * Validation messages.
     *
     * Editable because they are the words a visitor reads at the exact moment
     * they are stuck, and "Tell us your name." reads very differently from
     * "This field is required." Which field triggers which message is not
     * editable — that is the validation rule, not the wording.
     */
    errors: z.object({
      name: lead,
      organisation: lead,
      emailMissing: lead,
      emailInvalid: lead,
      /** "Choose a {topic}." — the select's own label, lowercased. */
      topic: lead,
      message: lead,
    }),
  }),
});

/* -------------------------------------------------------------------------
   Page copy
   ------------------------------------------------------------------------- */

export const homeCopySchema = z.object({
  meta: metaSchema,
  hero: z.object({
    /** Two lines so the second can take the accent colour. */
    headlineLine1: heading,
    headlineLine2: heading,
    /** "{competition} {year} / {venue}" */
    eyebrow: lead,
    specArchitectureLabel: microLabel,
    specTargetMassLabel: microLabel,
    specHeadcountLabel: microLabel,
  }),
  whatIsFs: sectionHeadingSchema.extend({
    /** "{competition} challenges university teams to..." */
    body: paragraph,
    judgingBody: paragraph,
    shippingBody: paragraph,
    /** Appended to site.programme.seasonOneLine. */
    seasonLine: paragraph,
    /** Labels for the three reference links. URLs live in site.json. */
    videoLinkLabel: linkLabel,
    officialLinkLabel: linkLabel,
    resultsLinkLabel: linkLabel,
    tbcLabel: microLabel,
    tbcTooltip: lead,
  }),
  countdown: z.object({
    eyebrow: eyebrow,
    /** "{class}, organised by the {organiser}." */
    note: lead,
  }),
  progress: sectionHeadingSchema.extend({
    allLink: linkLabel,
  }),
  news: sectionHeadingSchema.extend({
    allLink: linkLabel,
  }),
  sponsors: z.object({
    eyebrow: eyebrow,
    titleWithPartners: heading,
    titleEmpty: heading,
    leadWithPartners: lead,
    leadEmpty: lead,
    supportingHeading: subheading,
    /** "{amount}" is the cheapest cash tier, read from tiers.json. */
    entryLine: subheading,
    entryLineUnknown: subheading,
    entryBody: paragraph,
    partnerSince: microLabel,
    /** Alt text for a logo in the compact row. "{name} — {tier} partner" */
    logoAlt: shortLine,
  }),
  recruitment: z.object({
    eyebrow: eyebrow,
    title: heading,
    /** "{headcount} students across {subteams} subteams." */
    body: paragraph,
    teamLink: linkLabel,
  }),
});

export const becomeASponsorCopySchema = z.object({
  meta: metaSchema,
  header: z.object({
    eyebrow: eyebrow,
    title: heading,
    /** "...single-seater for {competition} {year}." */
    body: paragraph,
    tiersLink: buttonLabel,
    contactLink: buttonLabel,
  }),
  process: z.object({
    heading: subheading,
    steps: z.array(titledBodySchema).min(1).max(5),
    inKindNote: paragraph,
  }),
  reasons: sectionHeadingSchema.extend({
    tbcLabel: microLabel,
    tbcTooltip: lead,
  }),
  tiers: sectionHeadingSchema.extend({
    inKindFootnote: paragraph,
    liveryFootnote: paragraph,
    currencyFootnote: paragraph,
  }),
  inKind: sectionHeadingSchema.extend({
    body: paragraph,
    categories: z.array(titledBodySchema).min(1).max(10),
  }),
  enquiry: sectionHeadingSchema.extend({
    prospectusHeading: subheading,
    prospectusAvailable: paragraph,
    prospectusUnavailable: paragraph,
    prospectusRequestLabel: buttonLabel,
    prospectusRequestSubject: shortLine,
    prospectusDownloadLabel: buttonLabel,
    directHeading: subheading,
    formHeading: subheading,
    formNote: lead,
    tierLabel: microLabel,
    tierPlaceholder: linkLabel,
    messagePlaceholder: lead,
    /** Subject line on the sponsorship enquiry email. */
    formSubject: shortLine,
  }),
});

export const sponsorsCopySchema = z.object({
  meta: metaSchema,
  header: z.object({
    eyebrow: eyebrow,
    title: heading,
    lead: lead,
    asideHeading: subheading,
    totalLabel: microLabel,
    /** "Every tier is open for the {year} season." */
    asideNote: lead,
  }),
  partners: z.object({
    title: heading,
    emptyTitle: subheading,
    emptyBody: paragraph,
    emptyCta: buttonLabel,
    inKindNote: paragraph,
    partnerSince: microLabel,
    /** "Visit {name}" */
    visitLabel: microLabel,
  }),
  cta: z.object({
    title: heading,
    body: paragraph,
  }),
});

export const teamCopySchema = z.object({
  meta: metaSchema,
  about: z.object({
    eyebrow: eyebrow,
    /** "{organiser}" — what Formula Student is, for a reader who has never heard of it. */
    fsBody: paragraph,
    /** "KUFS represents {university} at {competition}, held at {venue}." */
    kufsBody: paragraph,
    asideHeading: subheading,
    headcountLabel: microLabel,
    subteamsLabel: microLabel,
    disciplinesLabel: microLabel,
    competingLabel: microLabel,
  }),
  values: z.object({
    title: heading,
  }),
  roster: sectionHeadingSchema.extend({
    operationsHeading: subheading,
    operationsBody: paragraph,
    engineeringHeading: subheading,
    engineeringBody: paragraph,
    vacantBadge: microLabel,
    vacantBody: paragraph,
    vacantLink: linkLabel,
    advisorHeading: subheading,
    joinLink: buttonLabel,
  }),
  cta: z.object({
    title: heading,
    body: paragraph,
  }),
});

export const theCarCopySchema = z.object({
  meta: metaSchema,
  /**
   * Status words for the eyebrow. Keys are fixed; the words are not.
   *
   * `inBuild` rather than `in-build`, which is the value in the car's JSON:
   * TinaCMS requires field names to be alphanumeric with underscores, and a
   * hyphen makes it refuse to load the config at all. The page maps between
   * the two, which is one line and better than either renaming a content enum
   * to suit a CMS or losing the field from the panel.
   */
  statusLabels: z.object({
    concept: microLabel,
    inBuild: microLabel,
    testing: microLabel,
    competing: microLabel,
    retired: microLabel,
  }),
  header: z.object({
    architectureLabel: microLabel,
    targetMassLabel: microLabel,
    buildLink: buttonLabel,
    posterCaption: captionLine,
  }),
  spec: z.object({
    eyebrow: eyebrow,
    title: heading,
    /** "{specified} of {total} rows have a value..." */
    lead: paragraph,
    /** Screen-reader caption. "Specification of the {name}." */
    tableCaption: lead,
    tbcLabel: microLabel,
    tbcTooltip: lead,
  }),
  subsystems: sectionHeadingSchema.extend({
    /** "Photography and CAD renders of the {system} package..." */
    noImageNote: paragraph,
  }),
  gallery: sectionHeadingSchema.extend({
    emptyBody: paragraph,
    emptyCta: buttonLabel,
  }),
});

export const progressCopySchema = z.object({
  meta: metaSchema,
  header: z.object({
    eyebrow: eyebrow,
    title: heading,
    lead: lead,
  }),
  timeline: sectionHeadingSchema,
  glossary: sectionHeadingSchema.extend({
    terms: z
      .array(
        z.object({
          /** The acronym as it appears in a milestone title, e.g. "DCS". */
          abbr: z.string().min(1).max(12),
          term: shortLine,
          definition: paragraph,
        }),
      )
      .min(1)
      .max(30),
  }),
  status: z.object({
    heading: subheading,
    completeLabel: microLabel,
    /** "Days to {event}" */
    daysToLabel: microLabel,
  }),
  preliminaryNote: paragraph,
  manufacturing: z.object({
    heading: subheading,
    label: shortLine,
    note: paragraph,
  }),
  updateLabel: microLabel,
  /** Shown where a milestone has no written update yet. */
  noUpdate: z.object({
    done: lead,
    active: lead,
    upcoming: lead,
  }),
  cta: z.object({
    title: heading,
    body: paragraph,
  }),
});

export const newsCopySchema = z.object({
  meta: metaSchema,
  header: z.object({
    eyebrow: eyebrow,
    title: heading,
    lead: lead,
  }),
  aside: z.object({
    heading: subheading,
    postsLabel: microLabel,
    subscribeLabel: microLabel,
    socialLabel: microLabel,
  }),
  listHeading: subheading,
  emptyTitle: subheading,
  emptyBody: paragraph,
  draftBadge: microLabel,
  /** The post page's own draft banner, which says more than the list badge. */
  post: z.object({
    draftBadge: microLabel,
    draftNote: paragraph,
    backLink: linkLabel,
    olderLink: linkLabel,
    newerLink: linkLabel,
    ctaTitle: heading,
    ctaBody: paragraph,
  }),
  rssLabel: linkLabel,
});

/**
 * /newsletter and /newsletter/[slug].
 *
 * Note what is NOT here: the subteam names. They are headings inside each
 * issue and they come from the roster's subteam list, so a subteam rename is
 * one edit and cannot leave the newsletter calling it the old thing.
 */
export const newsletterCopySchema = z.object({
  meta: metaSchema,
  header: z.object({
    eyebrow: eyebrow,
    title: heading,
    lead: lead,
  }),
  aside: z.object({
    heading: subheading,
    issuesLabel: microLabel,
    subscribeLabel: microLabel,
    latestLabel: microLabel,
  }),
  listHeading: subheading,
  /** "Issue {issue}" — on the index card and the issue page. */
  issueLabel: microLabel,
  /** Names the subteams that contributed, above the list on a card. */
  contributorsLabel: microLabel,
  /** "{count} subteams reporting" on the index card. */
  contributorCount: microLabel,
  emptyTitle: subheading,
  emptyBody: paragraph,
  emptyCta: buttonLabel,
  draftBadge: microLabel,
  rssLabel: linkLabel,
  issue: z.object({
    draftBadge: microLabel,
    draftNote: paragraph,
    backLink: linkLabel,
    /** Heading over the jump list of contributing subteams. */
    contentsHeading: subheading,
    introHeading: subheading,
    olderLink: linkLabel,
    newerLink: linkLabel,
    ctaTitle: heading,
    ctaBody: paragraph,
  }),
});

export const joinCopySchema = z.object({
  meta: metaSchema,
  header: z.object({
    eyebrow: eyebrow,
    title: heading,
    /** "KUFS is {headcount} students across {subteams} subteams." */
    body: paragraph,
    rolesLink: buttonLabel,
    teamLink: buttonLabel,
    asideHeading: subheading,
    headcountLabel: microLabel,
    subteamsLabel: microLabel,
    vacantLabel: microLabel,
    experienceLabel: microLabel,
    experienceValue: microLabel,
  }),
  gaps: sectionHeadingSchema.extend({
    vacantBadge: microLabel,
    /** "Nobody currently holds this. The {role} leads..." */
    vacantBody: paragraph,
    vacantSuited: paragraph,
    thinBadge: microLabel,
    thinBody: paragraph,
    thinSuited: paragraph,
  }),
  audience: sectionHeadingSchema.extend({
    body: paragraph,
    staticEventsNote: paragraph,
  }),
  roles: sectionHeadingSchema.extend({
    onSubteamLabel: microLabel,
    lookingForLabel: microLabel,
  }),
  season: sectionHeadingSchema,
  benefits: z.array(titledBodySchema).min(1).max(8),
  faq: sectionHeadingSchema.extend({
    items: z.array(faqSchema).min(1).max(12),
  }),
  apply: z.object({
    title: heading,
    body: paragraph,
    emailLabel: buttonLabel,
    /** Subject line of the application email. */
    emailSubject: shortLine,
    sponsorLink: buttonLabel,
  }),
});

export const pressKitCopySchema = z.object({
  meta: metaSchema,
  header: z.object({
    eyebrow: eyebrow,
    title: heading,
    lead: lead,
  }),
  comingSoon: paragraph,
  lockups: sectionHeadingSchema.extend({
    /** One caption per lockup, in the order they render. */
    captions: z.array(captionLine).length(4),
    clearSpaceNote: paragraph,
  }),
});

export const contactCopySchema = z.object({
  meta: metaSchema,
  header: z.object({
    eyebrow: eyebrow,
    title: heading,
    lead: lead,
  }),
  /**
   * Enquiry routes. `key` selects which address the row points at — that
   * mapping lives in the page, because an editor pointing "Press and media" at
   * the sponsorship inbox is a routing decision, not a wording one.
   */
  routes: sectionHeadingSchema.extend({
    answeredLabel: microLabel,
    items: z
      .array(
        z.object({
          key: z.enum(["sponsorship", "joining", "press", "general"]),
          label: subheading,
          blurb: paragraph,
          responseTime: shortLine,
        }),
      )
      .length(4),
  }),
  form: sectionHeadingSchema.extend({
    heading: subheading,
    note: lead,
    messagePlaceholder: lead,
    topicLabel: microLabel,
    topicPlaceholder: linkLabel,
    subject: shortLine,
  }),
  location: z.object({
    heading: subheading,
    teamLabel: microLabel,
    basedAtLabel: microLabel,
    city: shortLine,
    generalLabel: microLabel,
    followLabel: microLabel,
  }),
  sponsorNote: z.object({
    title: subheading,
    /** Split around the inline link, which is a route rather than a word. */
    bodyBefore: lead,
    linkLabel: linkLabel,
    bodyAfter: lead,
  }),
  /** Reply-time phrase used by the form on this page. */
  responseTime: shortLine,
});

export const notFoundCopySchema = z.object({
  meta: metaSchema,
  title: heading,
  body: paragraph,
  homeLink: buttonLabel,
  contactLink: buttonLabel,
});

/* -------------------------------------------------------------------------
   The copy registry
   ------------------------------------------------------------------------- */

/**
 * Every copy file, keyed by the name it has on disk.
 *
 * One entry per page plus `common`, mirroring the site rather than the
 * component tree — an editor with the live page open in another tab is looking
 * for the page they can see, not for the component that renders it.
 */
export const COPY_SCHEMAS = {
  common: commonCopySchema,
  home: homeCopySchema,
  "become-a-sponsor": becomeASponsorCopySchema,
  sponsors: sponsorsCopySchema,
  team: teamCopySchema,
  "the-car": theCarCopySchema,
  progress: progressCopySchema,
  news: newsCopySchema,
  newsletter: newsletterCopySchema,
  join: joinCopySchema,
  "press-kit": pressKitCopySchema,
  contact: contactCopySchema,
  "not-found": notFoundCopySchema,
} as const;

export type CopyKey = keyof typeof COPY_SCHEMAS;
export type Copy<K extends CopyKey> = z.infer<(typeof COPY_SCHEMAS)[K]>;

/* -------------------------------------------------------------------------
   Error reporting
   ------------------------------------------------------------------------- */

/**
 * Parse `data` or throw an error that names the file and the exact field.
 * A Zod stack trace in a Vercel build log is useless to the student editing
 * team.json at 2am; this is not.
 */
export function parseOrThrow<T extends z.ZodType>(
  schema: T,
  data: unknown,
  source: string,
): z.infer<T> {
  const result = schema.safeParse(data);
  if (result.success) return result.data;

  const issues = result.error.issues
    .map((issue) => {
      const path = issue.path.length ? issue.path.join(".") : "(root)";
      return `  • ${path}: ${issue.message}`;
    })
    .join("\n");

  throw new Error(
    `\n\nInvalid content in ${source}\n${issues}\n\n` +
      `Fix the file above, then re-run. Schemas live in src/lib/schemas.ts.\n`,
  );
}
