import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { MDXRemote } from "next-mdx-remote/rsc";

import { SpeedStripe } from "@/components/brand/SpeedStripe";
import { mdxComponents } from "@/components/news/mdxComponents";
import { Button } from "@/components/ui/Button";
import { Section } from "@/components/ui/Section";
import {
  getAdjacentIssues,
  getCopy,
  getIssueBySlug,
  getNav,
  getNewsletterIssues,
} from "@/lib/content";
import { issueMonth, issueTitle } from "@/lib/newsletter";

type Params = { slug: string };

/** Every issue is prerendered; there is no runtime data source. */
export function generateStaticParams(): Params[] {
  return getNewsletterIssues().map((issue) => ({ slug: issue.slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<Params>;
}): Promise<Metadata> {
  const { slug } = await params;
  const issue = getIssueBySlug(slug);
  if (!issue) return {};

  const copy = getCopy("newsletter");
  const title = issueTitle(issue, copy.issueLabel);

  return {
    title,
    description: issue.intro,
    alternates: { canonical: `/newsletter/${issue.slug}` },
    // Same rule as a draft news post: not indexable, and driven by the same
    // flag that keeps it out of the feed and the sitemap.
    robots: issue.draft ? { index: false, follow: false } : undefined,
    openGraph: {
      type: "article",
      title,
      description: issue.intro,
      url: `/newsletter/${issue.slug}`,
      publishedTime: `${issue.slug}-01`,
    },
    // No `images` key: an issue has no cover, so both of these fall through to
    // the site-wide card generated by src/app/opengraph-image.tsx — the same
    // route every other coverless page uses.
    twitter: { card: "summary_large_image", title, description: issue.intro },
  };
}

/**
 * A single newsletter issue.
 *
 * The shape is: editorial intro, a jump list of the subteams that contributed,
 * then one section each, then previous/next.
 *
 * THE JUMP LIST IS THE POINT OF THE PAGE. An issue with eight subteam reports
 * is long, and most readers want one of them — their own, or the one they
 * sponsor. It is a real `<nav>` with in-page links rather than a decorative
 * row of chips, so it is reachable by keyboard and announced as navigation.
 *
 * Each section renders as its own `<MDXRemote>` with the same components and
 * the same typographic styles as a news post. The `##` heading that named the
 * subteam has been consumed by the parser and is re-rendered here as the
 * section's `<h2>`, carrying the anchor id — which is why a subheading inside
 * a subteam's report must be `###`.
 */
export default async function NewsletterIssuePage({
  params,
}: {
  params: Promise<Params>;
}) {
  const copy = getCopy("newsletter");
  const nav = getNav();
  const { slug } = await params;
  const issue = getIssueBySlug(slug);
  if (!issue) notFound();

  const { previous, next } = getAdjacentIssues(slug);

  return (
    <>
      {/* ---------- Header ---------- */}
      <Section className="border-b border-border">
        <div className="mx-auto flex w-full max-w-[46rem] flex-col gap-5">
          <p className="text-caption">
            <Link
              href="/newsletter"
              className="font-semibold text-accent underline-offset-4 hover:underline"
            >
              {copy.issue.backLink}
            </Link>
          </p>

          <p className="text-eyebrow uppercase text-accent">
            {issueTitle(issue, copy.issueLabel)}
          </p>
          <h1 className="text-h1 text-text">{issueMonth(issue)}</h1>
          <SpeedStripe variant="accent" />

          <div>
            <h2 className="sr-only">{copy.issue.introHeading}</h2>
            <p className="text-lead text-text-muted">{issue.intro}</p>
          </div>

          {issue.draft ? (
            <div
              role="note"
              className="mt-2 rounded-lg border-2 border-status-upcoming/50 bg-surface p-5"
            >
              <p className="text-caption font-semibold uppercase tracking-widest text-status-upcoming">
                {copy.issue.draftBadge}
              </p>
              <p className="mt-2 text-small text-text-muted">{copy.issue.draftNote}</p>
            </div>
          ) : null}
        </div>
      </Section>

      {/* ---------- Contents + sections ---------- */}
      <Section>
        <div className="mx-auto w-full max-w-[46rem]">
          <nav
            aria-labelledby="contents-heading"
            className="mb-14 rounded-lg border border-border bg-surface p-6"
          >
            <h2
              id="contents-heading"
              className="text-caption uppercase tracking-wider text-text-muted"
            >
              {copy.issue.contentsHeading}
            </h2>
            <ul className="mt-3 flex flex-col gap-2">
              {issue.sections.map((section) => (
                <li key={section.id}>
                  <a
                    href={`#${section.id}`}
                    className="text-body font-semibold text-accent underline-offset-4 hover:underline"
                  >
                    {section.subteam}
                  </a>
                </li>
              ))}
            </ul>
          </nav>

          {issue.sections.map((section) => (
            <section
              key={section.id}
              aria-labelledby={section.id}
              className="mb-16 scroll-mt-28 border-t border-border pt-8"
            >
              <h2 id={section.id} className="text-h2 text-text">
                {section.subteam}
              </h2>
              <div className="mt-4">
                <MDXRemote source={section.body} components={mdxComponents} />
              </div>
            </section>
          ))}

          {/* ---------- Prev / next ---------- */}
          <nav
            aria-label="More issues"
            className="mt-16 grid gap-4 border-t border-border pt-10 sm:grid-cols-2"
          >
            {previous ? (
              <Link
                href={`/newsletter/${previous.slug}`}
                className="flex flex-col gap-1 rounded-lg border border-border bg-surface p-5 transition-colors hover:border-border-strong"
              >
                <span className="text-caption uppercase tracking-wider text-text-muted">
                  {copy.issue.olderLink}
                </span>
                <span className="text-h4 text-text">
                  {issueTitle(previous, copy.issueLabel)}
                </span>
              </Link>
            ) : (
              <span aria-hidden />
            )}

            {next ? (
              <Link
                href={`/newsletter/${next.slug}`}
                className="flex flex-col gap-1 rounded-lg border border-border bg-surface p-5 text-right transition-colors hover:border-border-strong sm:items-end"
              >
                <span className="text-caption uppercase tracking-wider text-text-muted">
                  {copy.issue.newerLink}
                </span>
                <span className="text-h4 text-text">
                  {issueTitle(next, copy.issueLabel)}
                </span>
              </Link>
            ) : null}
          </nav>
        </div>
      </Section>

      {/* ---------- CTA ---------- */}
      <Section tight className="border-t border-border">
        <div className="mx-auto flex w-full max-w-[46rem] flex-col items-start gap-5 rounded-lg border border-border bg-surface p-8">
          <h2 className="text-h3 text-text">{copy.issue.ctaTitle}</h2>
          <p className="max-w-[56ch] text-body text-text-muted">{copy.issue.ctaBody}</p>
          <div className="flex flex-col gap-3 sm:flex-row">
            <Button href={nav.cta.sponsor.href}>{nav.cta.sponsor.label}</Button>
            <Button href={nav.cta.join.href} variant="secondary">
              {nav.cta.join.label}
            </Button>
          </div>
        </div>
      </Section>
    </>
  );
}
